services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
  
  migrate:
    image: mysql:8
    container_name: migrate
    restart: "no"
    depends_on:
      - mysql
    entrypoint: >
      bash -c "
        sleep 30 &&
        mysql -h mysql -u root -proot orders < /docker-entrypoint-initdb.d/init.sql
      "
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 15s
      retries: 5

  ordersystem:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ordersystem
    depends_on:
      mysql:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      migrate:
        condition: service_started
    environment:
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orders
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      WEB_SERVER_PORT: ":8000"
      GRPC_SERVER_PORT: 50051
      GRAPHQL_SERVER_PORT: 8080
    ports:
      - "8080:8080"
      - "50051:50051"
      - "8000:8000"
    restart: unless-stopped